export const SET_CURRENT_SOUND = 'SET_CURRENT_SOUND';
export const SET_STANDARD_SOUNDS = 'SET_STANDARD_SOUNDS';
export const SET_ALT_SOUNDS = 'SET_ALT_SOUNDS';
export const UPDATE_STANDARD = 'UPDATE_STANDARD';
export const SET_POWER = 'SET_POWER';
export const UPDATE_ICON = 'UPDATE_ICON';
export const UPDATE_CURRENT_VOLUME = 'UPDATE_CURRENT_VOLUME';
export const SET_MUTED = 'SET_MUTED';
export const UPDATE_VOLUME_VALUE = 'UPDATE_VOLUME_VALUE';


